chore(action/PR): Use `pull_request_target` workflow

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -1,7 +1,8 @@
 name: PR
 
 on:
-  pull_request:
+  # "I am a workflow on the main branch's HEAD, target (base) of a PR"
+  pull_request_target:
     branches:
       - "main"
 
@@ -16,9 +17,9 @@ env:
   PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
   PR_HEAD_REPO: ${{ github.event.pull_request.head.repo.clone_url }}
 
-  # A synthetic read-only reference like `refs/pull/<id>/merge`
-  PR_MERGE_REF: ${{ github.ref }}
-  PR_MERGE_SHA: ${{ github.sha }}
+  # Full ref of base branch like `refs/heads/master`, gh_sha is same as base_sha
+  GH_REF: "${{ github.ref }}"
+  GH_SHA: ${{ github.sha }}
 
 jobs:
   lint-fmt:
@@ -28,20 +29,39 @@ jobs:
       - name: 🚚 Get latest code
         uses: actions/checkout@v3
         with:
-          # default ref = ${{ github.ref }} = pr_merge_ref (a merge commit)
-          # So, we checkout to PR's head commit instead
-          ref: ${{ env.PR_HEAD_SHA }}
-          fetch-depth: 0
+          # Checkout base (target) repo
+          ref: ${{ env.GH_REF }}
 
-      - name: 🥑 Install deps and git fetch
+      - name: 🥑 Install deps
         run: |
           npm install
-          git fetch --all
+
+      - name: 🍌 Fetch PR's head
+        run: |
+          git fetch origin ${{ env.PR_HEAD_SHA }}
+
+      # Abort if node modules are checked in
+      - name: 🚨 Check for unsafe changes
+        run: |
+          DIFF=$(git diff --name-only --diff-filter=ACMRT \
+            ${{ env.BASE_SHA }}...${{ env.PR_HEAD_SHA }})
+
+          echo "::notice::DIFF(files): $DIFF"
+
+          if echo $DIFF | grep "node_modules"; then
+            echo "::error::Unsafe change 'node_modules' found"
+            exit 1
+          fi
+
+      - name: 🍌 Checkout PR_HEAD
+        run: |
+          git checkout ${{ env.PR_HEAD_SHA }}
 
       - name: 🔧 Run eslint on changed files only
         run: |
           DIFF=$(git diff --name-only --diff-filter=ACMRT \
             ${{ env.BASE_SHA }}...${{ env.PR_HEAD_SHA }})
+
           npx eslint $DIFF --cache --fix
 
       - name: 👀 Look for lint changes
@@ -66,6 +86,11 @@ jobs:
         run: |
           git push origin HEAD:${{ env.PR_HEAD_REF }}
 
+      # `GITHUB_TOKEN` owned by `github-actions[bot]` has write access to
+      # origin in this `PR-target` workflow but not the write access to fork
+      # repo.
+      # A "personal access token" of repository maintainer may ne required
+      # for pushing to fork.
       - name: 🚢 Push to fork
         if: ${{ env.BASE_REPO != env.PR_HEAD_REPO }}
         run: |
